# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `declarative-builder` gem.
# Please instead update this file by running `bin/tapioca gem declarative-builder`.

module Declarative::Builder
  mixes_in_class_methods ::Declarative::Builder::DSL
  mixes_in_class_methods ::Declarative::Builder::Build

  class << self
    # @private
    #
    # source://declarative-builder//lib/declarative/builder.rb#5
    def included(base); end
  end
end

module Declarative::Builder::Build
  # Call this from your class to compute the concrete target class.
  #
  # source://declarative-builder//lib/declarative/builder.rb#36
  def build!(context, *args); end
end

class Declarative::Builder::Builders < ::Array
  # source://declarative-builder//lib/declarative/builder.rb#19
  def <<(proc); end

  # source://declarative-builder//lib/declarative/builder.rb#11
  def call(context, *args); end
end

module Declarative::Builder::DSL
  # source://declarative-builder//lib/declarative/builder.rb#25
  def builders; end

  # source://declarative-builder//lib/declarative/builder.rb#29
  def builds(proc = T.unsafe(nil), &block); end
end
