# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `guard-sorbet` gem.
# Please instead update this file by running `bin/tapioca gem guard-sorbet`.

# source://guard-sorbet//lib/guard/sorbet.rb#6
module Guard
  extend ::Guard::Internals::Helpers

  class << self
    # source://guard/2.18.0/lib/guard.rb#87
    def async_queue_add(changes); end

    # source://guard/2.18.0/lib/guard.rb#73
    def init(cmdline_options); end

    # source://guard/2.18.0/lib/guard.rb#24
    def interactor; end

    # source://guard/2.18.0/lib/guard.rb#23
    def listener; end

    # source://guard/2.18.0/lib/guard.rb#22
    def queue; end

    # source://guard/2.18.0/lib/guard.rb#44
    def setup(cmdline_options = T.unsafe(nil)); end

    # source://guard/2.18.0/lib/guard.rb#21
    def state; end

    private

    # source://guard/2.18.0/lib/guard.rb#132
    def _evaluate(options); end

    # source://guard/2.18.0/lib/guard.rb#152
    def _guardfile_deprecated_check(modified); end

    # source://guard/2.18.0/lib/guard.rb#113
    def _listener_callback; end

    # source://guard/2.18.0/lib/guard.rb#128
    def _pluginless_guardfile?; end

    # source://guard/2.18.0/lib/guard.rb#109
    def _relative_pathnames(paths); end

    # source://guard/2.18.0/lib/guard.rb#99
    def _relevant_changes?(changes); end
  end
end

# source://guard-sorbet//lib/guard/sorbet.rb#7
class Guard::Sorbet < ::Guard::Plugin
  # source://guard-sorbet//lib/guard/sorbet.rb#11
  sig { params(options: T.untyped).void }
  def initialize(options = T.unsafe(nil)); end

  # source://guard-sorbet//lib/guard/sorbet.rb#19
  sig { void }
  def run_all; end

  # source://guard-sorbet//lib/guard/sorbet.rb#34
  sig { params(_: T::Array[::String]).void }
  def run_on_modifications(_); end

  # source://guard-sorbet//lib/guard/sorbet.rb#29
  sig { void }
  def start; end
end
