#!/usr/bin/env ruby

require "caco"

ENV['CACO_ENV'] ||= 'development'
APP_PATH = File.expand_path('../', __dir__)
Caco.root = Pathname.new(APP_PATH)

Caco::SettingsLoader.(params: {
  keys_path: Caco.root.join("test", "fixtures", "keys"),
  data_path: Caco.root.join("test", "fixtures", "data")
})
