#!/usr/bin/env ruby

require "caco"

ENV['CACO_ENV'] ||= 'development'
APP_PATH = Bundler.root

Caco.root = Pathname.new(APP_PATH)

Caco::SettingsLoader.(params: {
  keys_path: Caco.root.join("keys"),
  data_path: Caco.root.join("data")
})

# puts "starting"

fqdn = Caco::Facter.("networking", "fqdn")
puts "[Caco] Running for: #{fqdn}"

begin
  require Caco.root.join("nodes", fqdn).to_s
rescue LoadError => e
  path = Caco.root.join("nodes", fqdn).to_s
  puts "Could not find manifest at #{path}.rb"
end

# puts "finishing"
